# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

QT += core xml

INCLUDEPATH += . .. ../..

TARGET = STLib
TEMPLATE = lib
CONFIG += staticlib

SOURCES += *.cpp
HEADERS += *.h

LIBS    += -L../../ShimLib -lvatlib

DESTDIR = ../../lib

unix {
    QMAKE_CXXFLAGS += -std=c++0x
    DEFINES += "VATLIB_STATIC"
    DEFINES += "NOSTDCALL"
    DEFINES += "DEFNULL"
}
