# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

QT += core xml

INCLUDEPATH += . .. ../..

TARGET = STLib
TEMPLATE = lib
CONFIG += staticlib

SOURCES += *.cpp
HEADERS += *.h

LIBS    += -L../../ShimLib -lvatlib

DESTDIR = ../../lib
