# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

QT += core xml

INCLUDEPATH += . .. ../..

TARGET = STd
TEMPLATE = app
CONFIG += console

SOURCES += *.cpp
HEADERS += *.h

LIBS    += -L../../lib -lSTLib -L../../ShimLib -lvatlib

DESTDIR = ../../bin

include(../../QtArg/qtarg.pri)

unix {
    QMAKE_CXXFLAGS += -std=c++0x
}
