# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

include(../common.pri)

QT += core xml
QT -= gui

INCLUDEPATH += . .. ../..

TARGET = STd
TEMPLATE = app
CONFIG += console
CONFIG += c++11

SOURCES += *.cpp
HEADERS += *.h

LIBS    += -L../../lib -lSTLib -lvatlib

DESTDIR = ../../bin

target.path = ../../dist/bin
INSTALLS += target
