# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

include(../common.pri)

QT += core xml
QT -= gui

INCLUDEPATH += . .. ../..

TARGET = STd
TEMPLATE = app
CONFIG += console

SOURCES += *.cpp
HEADERS += *.h

LIBS    += -L../../lib -lSTLib -lvatlib2

DESTDIR = ../../bin

include(../../QtArg/qtarg.pri)

unix {
    QMAKE_CXXFLAGS += -std=c++0x
}
